from fastapi import APIRouter, Query

from services.backtest_service import BacktestService

router = APIRouter()
backtester = BacktestService()


@router.get("/api/backtest/{symbol}")
def run_backtest(
    symbol: str,
    interval: str = "1h",
    market_type: str = "spot",
    start: str | None = None,
    end: str | None = None,
    initial_balance: float = Query(1000.0, gt=0),
    fee_rate: float = Query(0.001, ge=0),
    slippage_bps: float = Query(2.0, ge=0),
    allow_short: bool = False,
    leverage: float = Query(1.0, ge=1.0),
    maintenance_margin: float = Query(0.005, ge=0),
    max_qty: float = Query(10.0, gt=0),
    include_equity: bool = False,
    equity_stride: int = Query(1, ge=1),
    position_sizing_mode: str = "all_in",
    position_size_value: float | None = Query(None, gt=0),
    enable_volatility_scaling: bool = False,
    volatility_target_pct: float | None = Query(None, gt=0),
    min_volatility_scale: float | None = Query(0.50, gt=0),
    max_volatility_scale: float | None = Query(1.50, gt=0),    
    max_drawdown_pct: float | None = Query(None, gt=0),
    max_trades_per_day: int | None = Query(None, gt=0),
    cooldown_seconds: int = Query(0, ge=0),
    stop_loss_pct: float | None = Query(None, gt=0),
    take_profit_pct: float | None = Query(None, gt=0),
    exit_on_signal: bool = True,
    exit_mode: str = "static",
    atr_period: int = Query(14, gt=0),
    atr_stop_mult: float | None = Query(None, gt=0),
    atr_take_mult: float | None = Query(None, gt=0),
    atr_reference_mode: str = "entry",
    margin_mode: str = "isolated",
    enable_liquidation: bool = True,
    use_mark_price_for_liquidation: bool = True,
    mark_price_source: str = "close",
    liquidation_fee_rate: float = Query(0.005, ge=0),
    maintenance_margin_override: float | None = Query(None, gt=0, lt=1),
):
    return backtester.run_backtest(
        symbol=symbol,
        interval=interval,
        market_type=market_type,
        start=start,
        end=end,
        initial_balance=initial_balance,
        fee_rate=fee_rate,
        slippage_bps=slippage_bps,
        allow_short=allow_short,
        leverage=leverage,
        maintenance_margin=maintenance_margin,
        max_qty=max_qty,
        include_equity=include_equity,
        equity_stride=equity_stride,
        position_sizing_mode=position_sizing_mode,
        position_size_value=position_size_value,
        enable_volatility_scaling=enable_volatility_scaling,
        volatility_target_pct=volatility_target_pct,
        min_volatility_scale=min_volatility_scale,
        max_volatility_scale=max_volatility_scale,        
        max_drawdown_pct=max_drawdown_pct,
        max_trades_per_day=max_trades_per_day,
        cooldown_seconds=cooldown_seconds,
        stop_loss_pct=stop_loss_pct,
        take_profit_pct=take_profit_pct,
        exit_on_signal=exit_on_signal,        
        exit_mode=exit_mode,
        atr_period=atr_period,
        atr_stop_mult=atr_stop_mult,
        atr_take_mult=atr_take_mult,
        atr_reference_mode=atr_reference_mode,
        margin_mode=margin_mode,
        enable_liquidation=enable_liquidation,
        use_mark_price_for_liquidation=use_mark_price_for_liquidation,
        mark_price_source=mark_price_source,
        liquidation_fee_rate=liquidation_fee_rate,
        maintenance_margin_override=maintenance_margin_override,
    )

@router.get("/api/backtest_equity/{symbol}")
def backtest_equity(
    symbol: str,
    interval: str = "1h",
    market_type: str = "spot",
    leverage: float = 1.0,
    stride: int = Query(5, ge=1, le=200),
    exit_mode: str = "static",
    atr_period: int = 14,
    atr_stop_mult: float | None = None,
    atr_take_mult: float | None = None,
    atr_reference_mode: str = "entry",
    margin_mode: str = "isolated",
    enable_liquidation: bool = True,
    use_mark_price_for_liquidation: bool = True,
    mark_price_source: str = "close",
    liquidation_fee_rate: float = 0.005,
    maintenance_margin_override: float | None = None,
):
    res = backtester.run_backtest(
        symbol=symbol,
        interval=interval,
        market_type=market_type,
        leverage=leverage,
        include_equity=True,
        equity_stride=stride,
        exit_mode=exit_mode,
        atr_period=atr_period,
        atr_stop_mult=atr_stop_mult,
        atr_take_mult=atr_take_mult,
        atr_reference_mode=atr_reference_mode,
        margin_mode=margin_mode,
        enable_liquidation=enable_liquidation,
        use_mark_price_for_liquidation=use_mark_price_for_liquidation,
        mark_price_source=mark_price_source,
        liquidation_fee_rate=liquidation_fee_rate,
        maintenance_margin_override=maintenance_margin_override,
    )

    return {
        "symbol": res["symbol"],
        "interval": res["interval"],
        "market_type": res["market_type"],
        "equity_curve": res.get("equity_curve", []),
        "risk_events": res.get("risk_events", []),
        "last_margin_snapshot": res.get("last_margin_snapshot"),
        "max_margin_ratio": res.get("max_margin_ratio"),
        "closest_liquidation_distance_pct": res.get("closest_liquidation_distance_pct"),
    }
